buildblog/apps/blog/urls.py
from django import urls
from django.urls import path

from .views import *

app_name = "blog"

urlpatterns = [
    path('blogs/', TechStackListView.as_view(), name='tech_list'),
    path('blogs/<slug:slug>/', BlogListView.as_view(), name='blog_list'),
    path('blogs/<slug:slug>/<str:str>/', BlogAPIView.as_view(), name='blog_api'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('like/', LikeView, name='blog_likes'),
    path('tech/trends/', TechStackListView.as_view(), name='trend_list'),
]

buildblog/apps/core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ActivateAccount, SignUpView, contact, UserProfileView
from django.contrib.auth import views as auth_views
from core.views import DocumentView

app_name='core'

urlpatterns = [
    path('join/', SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),

    path('login/', auth_views.LoginView.as_view(next_page='core:home'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='core:home'), name='logout'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),

    # Change Password
    path('change-password/', auth_views.PasswordChangeView.as_view( template_name='core/change-password.html', success_url='/'), name='change_password'),

    # Forget Password
    path('password-reset/', auth_views.PasswordResetView.as_view( template_name='core/password-reset/password_reset.html', subject_template_name='core/password-reset/password_reset_subject.html', email_template_name='core/password-reset/password_reset_email.html', success_url='/login/' ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='core/password-reset/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='core/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view( template_name='core/password-reset/password_reset_complete.html' ), name='password_reset_complete'),
    
    # Main Page
    path('about/', TemplateView.as_view(template_name='commons/about.html'), name='about'),
    path("contact/", contact, name="contact_us"),
    path('', DocumentView.as_view(), name='home')
]

buildblog/urls.py
from django.views.generic import TemplateView
from core import urls as core_urls
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from blog.views import  TechStackListView
from core.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', include('blog.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

buildblog/apps/blog/models.py
from distutils.command.upload import upload
from email.mime import image
from email.policy import default
from urllib.parse import urlparse
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from core.models import BaseModel
from django.utils.translation import gettext_lazy as _
from common.app_utils import unique_media_upload, icon_media_upload
from django.core.validators import FileExtensionValidator
from ckeditor_uploader.fields import RichTextUploadingField 

User = get_user_model()


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="published")


TECHNOLOGY_TYPE_CHOICES = (
    (1, _("Programing Language")),
    (2, _("Database")),
    (3, _("Framework")),
    (4, _("Cloud Service")),
    (5, _("Web Server")),
    (6, _("Library")),
    (7, _("Git Platform")),
)


class Technology(BaseModel):
    name = models.CharField(_('Title'), max_length=250)
    platform = models.IntegerField(choices=TECHNOLOGY_TYPE_CHOICES, default=1)
    icon = models.FileField(upload_to= icon_media_upload, validators=[FileExtensionValidator(['svg'])])
    background_image = models.ImageField(upload_to = unique_media_upload, null=True, blank=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = "Technology"

    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    @property
    def image_url(self):
        try:
            url = self.img.url
        except:
            url=''
        return url


class Blog(BaseModel):
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(max_length=40)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blog_users")
    contents = RichTextUploadingField()
    image = models.ImageField(upload_to=unique_media_upload)
    video = models.FileField(upload_to=unique_media_upload, null=True, blank=True)
    published_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")
    published = PublishedManager()
    url = models.URLField(max_length=400)
    related_technology = models.ManyToManyField(Technology)
    sub_title = models.CharField(max_length=254)
    objects = models.Manager()
    published = PublishedManager()
    point = models.IntegerField(default=0)
    primary_technology = models.ForeignKey(Technology, related_name="blog_technologies", on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, default=None, blank=True, related_name='like')
    like_count = models.BigIntegerField(default='0')

    class Meta:
        ordering = ("-published_at",)

    def url_text(self):
        parsed_url = urlparse(self.url)
        return parsed_url.hostname

    def get_absolute_url(self):
        return reverse('blog_list', kwargs={'slug': self.slug})

    def __str__(self):
        return f"{self.title}"
    
    def total_likes(self):
        return self.likes.all().count()


class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=70, default="")
    phone = models.CharField(max_length=70, default="")
    desc = models.CharField(max_length=500, default="")

    def __str__(self):
        return self.name

buildblog/apps/blog/views.py
import json
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
# specific to this view
from django.views.generic import ListView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic.edit import CreateView
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

from .models import Blog,Technology
import datetime
from django.core.serializers.json import DjangoJSONEncoder
from rest_framework.views import APIView
from blog.serializers import BlogSerializer
from rest_framework.response import Response
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect


class BlogListView(ListView):
    queryset = Blog.published.all()
    template_name = 'blogs/blog_list.html' 
    ordering = ['-published_at']
    paginate_by = 10
    slug_url_kwarg= 'slug'
    context_object_name = 'blogs'


    def get_queryset(self):
        self.queryset = self.queryset.filter(primary_technology__slug=self.kwargs.get('slug'))
        if 'days' in self.request.GET:
            today = datetime.date.today()
            days = today - datetime.timedelta(days=int(self.request.GET.get('days')))
            self.queryset = self.queryset.filter(published_at__gte=days)
           
        return self.queryset
            

    def get_context_data(self, *args, object_list=None, **kwargs):
        
        today = datetime.date.today()
        context_data= super().get_context_data(object_list=self.queryset,*args,**kwargs)
        slug_data = self.kwargs.get('slug')
        current_year = datetime.datetime.now().year
        blog_count=self.object_list.count()
        context_data['page_title'] = f"{slug_data} Blogs"
        context_data['tech_slug'] = slug_data
        context_data['str'] = slug_data
        context_data['title']= f"{blog_count} Best {slug_data} blogs to Read in {current_year}"
        context_data['today'] =self.object_list.filter(published_at__gte=today)
        if 'days' in self.request.GET: 
            temp = render_to_string("blogs/_partial_list2.html", {"data": object_list})
           
            return JsonResponse({'data': temp })
        return context_data 


class BlogAPIView(APIView):
    queryset = Blog.published.all()
    serializer_class= BlogSerializer
    template_name = 'blogs/blog_list.html'

    def get_queryset(self):
        self.queryset = self.queryset.filter(primary_technology__slug=self.kwargs.get('slug'))
        if 'days' in self.request.GET:
            
            today = datetime.date.today()
            days = today - datetime.timedelta(days=int(self.request.GET.get('days')))
            
            self.queryset = self.queryset.filter(published_at__gte=days)
           
        return self.queryset
            

    def get(self, request, object_list=None, **kwargs):
        object_list= self.get_queryset()
        today = datetime.date.today()
        items = object_list.filter(primary_technology__slug=self.kwargs.get('slug'))
        if 'days' in self.request.GET: 
            temp = render_to_string("blogs/_partial_list2.html", {"data": items})
            return JsonResponse({'data': temp })
        return items 


class TechStackListView(ListView):
    queryset = Technology.objects.all()
    template_name = 'blogs/listing_page.html'
    context_object_name = 'techs'
    paginate_by = 41
    model= Technology
    success_url = reverse_lazy('blog_list')

    def get_context_data(self, *,object_list=None ,**kwargs):
        context_data = super().get_context_data(**kwargs)
     
        return context_data

#   blog search
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        
        keyword = self.request.GET.get('keyword')
        if keyword:
            return queryset.filter(name__icontains = keyword)
        return queryset



@method_decorator(login_required, name='dispatch')
class BlogCreateView(CreateView):
    model = Blog
    template_name = 'blogs/blog_form.html'

    fields = ['title', 'sub_title', 'url', 'primary_technology','related_technology', 'video','image','contents']
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


# @method_decorator(login_required, name='dispatch')
class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blogs/blog_detail.html'
    context_object_name = 'blogs'
    fields = ['title', 'contents', 'image', 'video', 'url']


@method_decorator(login_required, name='dispatch')
class BlogUpdateView(UpdateView):
    model = Blog
    slug_url_kwarg = 'slug'
    template_name = 'blogs/blog_update.html'
    context_object_name = 'blogs'
    fields = ['title', 'primary_technology','image', 'video', 'url', 'contents',]
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        blog = self.get_object()
        if self.request.user == blog.author:
            return True
        return False
        

    def get_success_url(self):
        return reverse_lazy('tech_list')
        # return reverse_lazy('blog:blog_list', kwargs={'slug': self.slug})


@method_decorator(login_required, name='dispatch')
class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blogs/blog_confirm_delete.html'
    success_url = reverse_lazy('blog:blog_list') 

@login_required
def LikeView(request):
    if request.POST.get('action')=='post':
        result=''
        id = str(request.POST.get('postid'))
        blog = get_object_or_404(Blog , id = id)
    
        if blog.likes.filter(id=request.user.id).exists():
           blog.likes.remove(request.user)
           blog.like_count-=1
           result=blog.like_count
           blog.save()
        else:
           blog.likes.add(request.user)
           blog.like_count+=1
           result=blog.like_count
           blog.save()
    return JsonResponse({'result':result})
    

buildblog/apps/core/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import get_callable, reverse, reverse_lazy
from django.views.generic import View, UpdateView, FormView, CreateView, TemplateView
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string

from core.tokens import account_activation_token
from django.core.mail import EmailMessage, send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.template.defaulttags import csrf_token
from django.contrib.auth import login, authenticate, get_user_model
from django.views.decorators.csrf import csrf_protect
from core.forms import *

User = get_user_model()

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        desc = request.POST.get('desc', '')
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
        return redirect('home')
    return render(request, 'commons/contact.html')



class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        User = get_user_model()
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)

        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            messages.success(request, 'Your account have been confirmed.')
            return redirect('home')
        else:
            messages.warning(request, 'The confirmation link was invalid, possibly because it has already been used.')
            return redirect('home')


class DocumentView(TemplateView):
    template_name = 'commons/home.html'
    model=User
    
    def get_context_data(self, *args, **kwargs):
        context_data= super(DocumentView,self).get_context_data(*args, **kwargs)
        context_data['user_count'] = User.objects.all().count()
        return context_data

class SignUpView(FormView):
    form_class = RegistrationForm
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        user = form.save(False)
        user.set_password(form.cleaned_data.get('password1'))
        user.is_active = False  # Deactivate account till it is confirmed

        current_site = get_current_site(self.request)
        mail_subject = 'Activate Account'
        message = render_to_string('emails/account_activation_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage( mail_subject, message, to=[to_email])
        email.send()
        messages.success(self.request, 'Please Confirm your email to complete registration.')
        user.save()
        return HttpResponseRedirect(reverse('home'))



class UserProfileView(LoginRequiredMixin, UpdateView): #Note that we are using UpdateView and not FormView
    model = User
    form_class = UserProfileForm
    template_name = "registration/profile.html"
    context_object_name = 'user'
    login_url = '/accounts/login/'

    def get_success_url(self, *args, **kwargs):
        return reverse("core:home")

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['form'] = UserProfileForm(instance=self.request.user)
        return context

buildblog/templates/commons/layout/footer.html
<div class="footer">
    <div class="footerBox">
        <div>
            {% if user.is_authenticated %}
                <a aria-current="page" class="footerHeading" href="{% url 'blog:blog_create' %}">BuildBlog for Developers</a>
            {% else %}
                <a aria-current="page" class="footerHeading"><button class="sm-text btn btn-dark" href="{% url 'core:login' %}?next={{request.path}}">BuildBlog for Developers</button></a>
            {% endif %}
            <span class="footerSubheading">Developed  by<!-- -->
                <a href="https://twitter.com/vksipl027" target="_blank" rel="noopener" class="darkBox">@VK</a>
            </span>
            <span class="footerSubheading">Made by<!-- -->
                <a href="https://www.santophy.com/" target="_blank" rel="noopener" class="darkBox">@SIPL</a>
            </span>
            <p class="pt-3 pb-3">Learn how to grow your blog as a developer without an existing audience through great writing and SEO.</p>
            <ul class="firstList">
                <li><a aria-current="page" class="" href="{% url 'core:home' %}">Home</a></li>
                <li><a href="{% url 'core:contact_us' %}">Contact</a></li>
                <li><a href="javascript:void(0)">Impressum</a></li>
                <li><a href="javascript:void(0)">Become a Sponsor</a></li>
            </ul>
        </div>
        <div class="footerListBox">
            <div>
                <div class="listHeading">Resources</div>
                <ul class="listBox">
                    <li><a aria-current="page" class="" href="javascript:void(0)">Free Course</a></li>
                    <li><a href="{% url 'blog:tech_list' %}">Blog</a></li>
                    <li><a href="javascript:void(0)">Interviews</a></li>
                    <li><a href="https://seofordevs.com/" target="_blank">SEO for Developers</a></li>
                    <li><a href="javascript:void(0)">Developer Blogs</a></li>
                    <li><a aria-current="page" class="view-all" href="{% url 'core:home' %}">Home</a></li>
                </ul>
            </div>
            <div>
                <div class="listHeading">Community</div>
                <ul class="listBox">
                    {% if user.is_authenticated %}
                        <button id="login-ft" class="footerBtn" tabindex="0" type="button">
                            <span class="footerLabel"><a href="{% url 'core:logout' %}">LOG OUT</a></span>
                        </button>
                    {% else %}
                        <li> <a href="{% url 'core:signup' %}"><button id="signup-ft" class="footerBtn" tabindex="0" type="button" >
                            <span class="footerLabel">Join Us</span></a>
                        </button> <span class="css-1hvhxos">New</span></li>
                        <!-- <li><a id="signup-ft">Join Us</a> <span class="css-1hvhxos">New</span></li> -->
                        <li><a href="{% url 'core:password_reset' %}">Reset Password</a></li>
                        <button id="login-ft" class="footerBtn" tabindex="0" type="button">
                            <span class="footerLabel"> <a  href="{% url 'core:login' %}?next={{request.path}}">LOG IN</a></span>
                        </button>
                    {% endif %}
                    <li><a href="javascript:void(0)">Live Events</a></li>
                </ul>
            </div>
            <div>
                <div class="listHeading">Discover</div>
                <ul class="listBox">
                    <li><a href="{% url 'blog:blog_list' slug='javascript' %}">JavaScript Blogs</a></li>
                    <li><a href="{% url 'blog:blog_list' slug='python' %}">Python Blogs</a></li>
                    <li><a href="{% url 'blog:blog_list' slug='ruby' %}">Ruby Blogs</a></li>
                    <li><a href="{% url 'blog:blog_list' slug='react' %}">React.js Blogs</a></li>
                    <li><a class="view-all" href="{% url 'blog:tech_list' %}">View All</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

buildblog/templates/commons/layout/header.html
{% load static %}
<header class="header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/"><img src="{% static 'img/logo.png' %}" alt="" class="logo-img"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog:tech_list' %}">Blogs</a>
                    <a class="nav-item nav-link" href="{% url 'core:about' %}">About</a>
                    <a class="nav-item nav-link" href="{% url 'core:contact_us' %}">Contact</a>
                </div>

                <!-- slug=technology.slug  -->
                <!-- Navbar Right Side -->

                <div class="navbar-nav">
                    {% if request.user.is_authenticated %}
                        <div class="dropdown">
                          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                          </button>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" style="margin-right: -5px;" href="{% url 'core:profile' user.id %}">Profile</a>
                            <a class="dropdown-item" style="margin-top: 8px;" href="{% url 'core:change_password' %}">Change Password</a>
                            <a class="dropdown-item" style="margin-top: 8px;" href="{% url 'core:logout' %}">Logout</a>
                          </div>
                        </div>
                    {% else %}
                        <a class="nav-item nav-link" style="margin-right: -15px;" id="login-btn" class="btn nav-link" type="button" href="{% url 'core:login' %}?next={{request.path}}">Login</a>&nbsp;
                        <a class="nav-item nav-link" style="margin-right: -7px;" class="btn nav-link" type="button" href="{% url 'core:signup' %}">Join Us</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </nav>

</header>

buildblog/templates/commons/layout/page_header.html
<div class="header">
    <div class="contentSection">
        <div class="darkHeadingBox">
            <a mode="light" class="darkHeading" href="{% url 'blog:trend_list' %}">BuildBlog for Developer<div class="headingBox">Trends</div></a>
            {% if user.is_authenticated %}
                <div mode="light" class="lgHeadingBox">It's free:<a class="css-8sfwpu" href="{% url 'blog:blog_create' %}">BuildBlog for Developers</a></div>
            {% else %}
                <div mode="light" class="lgHeadingBox">It's free:<botton class="css-8sfwpu btn btn-light " href="{% url 'core:login' %}?next={{request.path}}">BuildBlog for Developers</botton></div>
            {% endif %}
        </div>
        <div class="contentBox">
            <h1>{{title}}</h1>
            <div mode="light" class="text"><strong>Updated Hourly</strong> (<a href="#">How it Works</a>)
            </div>
        </div>
    </div>
</div>