buildblog/apps/blog/urls.py
from django import urls
from django.urls import path

from .views import *

app_name = "blog"

urlpatterns = [
    path('blogs/', TechStackListView.as_view(), name='tech_list'),
    path('blogs/<slug:slug>/', BlogListView.as_view(), name='blog_list'),
    path('blogs/<slug:slug>/<str:str>/', BlogAPIView.as_view(), name='blog_api'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('like/', LikeView, name='blog_likes'),
    path('tech/trends/', TechStackListView.as_view(), name='trend_list'),
]

buildblog/apps/core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ActivateAccount, SignUpView, contact, UserProfileView
from django.contrib.auth import views as auth_views
from core.views import DocumentView

app_name='core'

urlpatterns = [
    path('join/', SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),

    path('login/', auth_views.LoginView.as_view(next_page='core:home'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='core:home'), name='logout'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),

    # Change Password
    path('change-password/', auth_views.PasswordChangeView.as_view( template_name='core/change-password.html', success_url='/'), name='change_password'),

    # Forget Password
    path('password-reset/', auth_views.PasswordResetView.as_view( template_name='core/password-reset/password_reset.html', subject_template_name='core/password-reset/password_reset_subject.html', email_template_name='core/password-reset/password_reset_email.html', success_url='/login/' ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='core/password-reset/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='core/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view( template_name='core/password-reset/password_reset_complete.html' ), name='password_reset_complete'),
    
    # Main Page
    path('about/', TemplateView.as_view(template_name='commons/about.html'), name='about'),
    path("contact/", contact, name="contact_us"),
    path('', DocumentView.as_view(), name='home')
]

buildblog/urls.py
from django.views.generic import TemplateView
from core import urls as core_urls
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from blog.views import  TechStackListView
from core.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', include('blog.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

buildblog/apps/blog/models.py
from distutils.command.upload import upload
from email.mime import image
from email.policy import default
from urllib.parse import urlparse
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from core.models import BaseModel
from django.utils.translation import gettext_lazy as _
from common.app_utils import unique_media_upload, icon_media_upload
from django.core.validators import FileExtensionValidator
from ckeditor_uploader.fields import RichTextUploadingField 

User = get_user_model()


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="published")


TECHNOLOGY_TYPE_CHOICES = (
    (1, _("Programing Language")),
    (2, _("Database")),
    (3, _("Framework")),
    (4, _("Cloud Service")),
    (5, _("Web Server")),
    (6, _("Library")),
    (7, _("Git Platform")),
)


class Technology(BaseModel):
    name = models.CharField(_('Title'), max_length=250)
    platform = models.IntegerField(choices=TECHNOLOGY_TYPE_CHOICES, default=1)
    icon = models.FileField(upload_to= icon_media_upload, validators=[FileExtensionValidator(['svg'])])
    background_image = models.ImageField(upload_to = unique_media_upload, null=True, blank=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = "Technology"

    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    @property
    def image_url(self):
        try:
            url = self.img.url
        except:
            url=''
        return url


class Blog(BaseModel):
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(max_length=40)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blog_users")
    contents = RichTextUploadingField()
    image = models.ImageField(upload_to=unique_media_upload)
    video = models.FileField(upload_to=unique_media_upload, null=True, blank=True)
    published_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")
    published = PublishedManager()
    url = models.URLField(max_length=400)
    related_technology = models.ManyToManyField(Technology)
    sub_title = models.CharField(max_length=254)
    objects = models.Manager()
    published = PublishedManager()
    point = models.IntegerField(default=0)
    primary_technology = models.ForeignKey(Technology, related_name="blog_technologies", on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, default=None, blank=True, related_name='like')
    like_count = models.BigIntegerField(default='0')

    class Meta:
        ordering = ("-published_at",)

    def url_text(self):
        parsed_url = urlparse(self.url)
        return parsed_url.hostname

    def get_absolute_url(self):
        return reverse('blog_list', kwargs={'slug': self.slug})

    def __str__(self):
        return f"{self.title}"
    
    def total_likes(self):
        return self.likes.all().count()


class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=70, default="")
    phone = models.CharField(max_length=70, default="")
    desc = models.CharField(max_length=500, default="")

    def __str__(self):
        return self.name

buildblog/apps/blog/views.py
import json
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
# specific to this view
from django.views.generic import ListView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic.edit import CreateView
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

from .models import Blog,Technology
import datetime
from django.core.serializers.json import DjangoJSONEncoder
from rest_framework.views import APIView
from blog.serializers import BlogSerializer
from rest_framework.response import Response
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect


class BlogListView(ListView):
    queryset = Blog.published.all()
    template_name = 'blogs/blog_list.html' 
    ordering = ['-published_at']
    paginate_by = 10
    slug_url_kwarg= 'slug'
    context_object_name = 'blogs'


    def get_queryset(self):
        self.queryset = self.queryset.filter(primary_technology__slug=self.kwargs.get('slug'))
        if 'days' in self.request.GET:
            today = datetime.date.today()
            days = today - datetime.timedelta(days=int(self.request.GET.get('days')))
            self.queryset = self.queryset.filter(published_at__gte=days)
           
        return self.queryset
            

    def get_context_data(self, *args, object_list=None, **kwargs):
        
        today = datetime.date.today()
        context_data= super().get_context_data(object_list=self.queryset,*args,**kwargs)
        slug_data = self.kwargs.get('slug')
        current_year = datetime.datetime.now().year
        blog_count=self.object_list.count()
        context_data['page_title'] = f"{slug_data} Blogs"
        context_data['tech_slug'] = slug_data
        context_data['str'] = slug_data
        context_data['title']= f"{blog_count} Best {slug_data} blogs to Read in {current_year}"
        context_data['today'] =self.object_list.filter(published_at__gte=today)
        if 'days' in self.request.GET: 
            temp = render_to_string("blogs/_partial_list2.html", {"data": object_list})
           
            return JsonResponse({'data': temp })
        return context_data 


class BlogAPIView(APIView):
    queryset = Blog.published.all()
    serializer_class= BlogSerializer
    template_name = 'blogs/blog_list.html'

    def get_queryset(self):
        self.queryset = self.queryset.filter(primary_technology__slug=self.kwargs.get('slug'))
        if 'days' in self.request.GET:
            
            today = datetime.date.today()
            days = today - datetime.timedelta(days=int(self.request.GET.get('days')))
            
            self.queryset = self.queryset.filter(published_at__gte=days)
           
        return self.queryset
            

    def get(self, request, object_list=None, **kwargs):
        object_list= self.get_queryset()
        today = datetime.date.today()
        items = object_list.filter(primary_technology__slug=self.kwargs.get('slug'))
        if 'days' in self.request.GET: 
            temp = render_to_string("blogs/_partial_list2.html", {"data": items})
            return JsonResponse({'data': temp })
        return items 


class TechStackListView(ListView):
    queryset = Technology.objects.all()
    template_name = 'blogs/listing_page.html'
    context_object_name = 'techs'
    paginate_by = 41
    model= Technology
    success_url = reverse_lazy('blog_list')

    def get_context_data(self, *,object_list=None ,**kwargs):
        context_data = super().get_context_data(**kwargs)
     
        return context_data

#   blog search
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        
        keyword = self.request.GET.get('keyword')
        if keyword:
            return queryset.filter(name__icontains = keyword)
        return queryset



@method_decorator(login_required, name='dispatch')
class BlogCreateView(CreateView):
    model = Blog
    template_name = 'blogs/blog_form.html'

    fields = ['title', 'sub_title', 'url', 'primary_technology','related_technology', 'video','image','contents']
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


# @method_decorator(login_required, name='dispatch')
class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blogs/blog_detail.html'
    context_object_name = 'blogs'
    fields = ['title', 'contents', 'image', 'video', 'url']


@method_decorator(login_required, name='dispatch')
class BlogUpdateView(UpdateView):
    model = Blog
    slug_url_kwarg = 'slug'
    template_name = 'blogs/blog_update.html'
    context_object_name = 'blogs'
    fields = ['title', 'primary_technology','image', 'video', 'url', 'contents',]
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        blog = self.get_object()
        if self.request.user == blog.author:
            return True
        return False
        

    def get_success_url(self):
        return reverse_lazy('tech_list')
        # return reverse_lazy('blog:blog_list', kwargs={'slug': self.slug})


@method_decorator(login_required, name='dispatch')
class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blogs/blog_confirm_delete.html'
    success_url = reverse_lazy('blog:blog_list') 

@login_required
def LikeView(request):
    if request.POST.get('action')=='post':
        result=''
        id = str(request.POST.get('postid'))
        blog = get_object_or_404(Blog , id = id)
    
        if blog.likes.filter(id=request.user.id).exists():
           blog.likes.remove(request.user)
           blog.like_count-=1
           result=blog.like_count
           blog.save()
        else:
           blog.likes.add(request.user)
           blog.like_count+=1
           result=blog.like_count
           blog.save()
    return JsonResponse({'result':result})
    

buildblog/apps/core/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import get_callable, reverse, reverse_lazy
from django.views.generic import View, UpdateView, FormView, CreateView, TemplateView
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string

from core.tokens import account_activation_token
from django.core.mail import EmailMessage, send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.template.defaulttags import csrf_token
from django.contrib.auth import login, authenticate, get_user_model
from django.views.decorators.csrf import csrf_protect
from core.forms import *

User = get_user_model()

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        desc = request.POST.get('desc', '')
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
        return redirect('home')
    return render(request, 'commons/contact.html')



class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        User = get_user_model()
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)

        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            messages.success(request, 'Your account have been confirmed.')
            return redirect('home')
        else:
            messages.warning(request, 'The confirmation link was invalid, possibly because it has already been used.')
            return redirect('home')


class DocumentView(TemplateView):
    template_name = 'commons/home.html'
    model=User
    
    def get_context_data(self, *args, **kwargs):
        context_data= super(DocumentView,self).get_context_data(*args, **kwargs)
        context_data['user_count'] = User.objects.all().count()
        return context_data

class SignUpView(FormView):
    form_class = RegistrationForm
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        user = form.save(False)
        user.set_password(form.cleaned_data.get('password1'))
        user.is_active = False  # Deactivate account till it is confirmed

        current_site = get_current_site(self.request)
        mail_subject = 'Activate Account'
        message = render_to_string('emails/account_activation_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage( mail_subject, message, to=[to_email])
        email.send()
        messages.success(self.request, 'Please Confirm your email to complete registration.')
        user.save()
        return HttpResponseRedirect(reverse('home'))



class UserProfileView(LoginRequiredMixin, UpdateView): #Note that we are using UpdateView and not FormView
    model = User
    form_class = UserProfileForm
    template_name = "registration/profile.html"
    context_object_name = 'user'
    login_url = '/accounts/login/'

    def get_success_url(self, *args, **kwargs):
        return reverse("core:home")

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['form'] = UserProfileForm(instance=self.request.user)
        return context

buildblog/templates/blogs/_partial_list2.html
{% load static %}
{% load social_share %}
<div>
    <div class="blogContainer">
        <div class="tab-content" id="filteredBlogs">
                {% for blog in object_list %}
                    <div class="blogBox">
                        <div class="blogImg"><img alt="{{blog.title}}" src="{{blog.image.url}}" class="bgImg1"></div>
                        <div class="blogDesc">
                            <h3 class="lgHeading"><a href="{% url 'blog:blog_detail' blog.id %}" rel="noopener">{{ forloop.counter }}. {{ blog.title }}</a></h3>
                            <p class="blogPara">{{blog.contents|safe}}</p>
                            <div class="smHeading">TRENDING POST:</div>
                                <a href="{{blog.url}}" target="_blank" rel="noopener" class="blogNote">{{blog.sub_title}}</a><br><br>
                                <div>
                                    {% for r_tech in blog.related_technology.all  %}
                                        <a aria-current="page" variant="blue" class="smLabel">{{r_tech.name}}</a>
                                    {% endfor %}
                                    <a aria-current="page" variant="blue" class="smLabel" href="{% url 'blog:blog_detail' blog.id %}">View</a>
                                    <span class="smIcon">
                                        <a href="https://twitter.com/intent/tweet?text=New%20Song%3A%20W3.%20Check%20it%20out%21%20http%3A//127.0.0.1%3A8000/blogs/python/" target="_blank" rel="noopener">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                                <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path>
                                            </svg>
                                        </a>
                                    </span>
                                </div>
                            </div>
                            <div class="rgtSide">
                                <div class="sideBox">
                                    <span class="sideIcon" >
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline><polyline points="17 6 23 6 23 12"></polyline>
                                        </svg>
                                    </span>
                                    <div class="sideHeading">{{blog.point}}</div>
                                    <div class="sideText">points</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>  
            </div>
</div>

buildblog/templates/blogs/blog_confirm_delete.html
{% extends "__base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <h2 style="margin-top: 60px;">Are you sure you want to delete the blog "{{ object.title }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'blog:blog_detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

buildblog/templates/blogs/blog_detail.html
{% extends "__base.html" %}
{% block content %}
<div class="article__head">
  <div class="article__content">
    <article class="media content-section">
      <!--  <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">-->
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="#">{{ object.author }}</a>
          <small class="text-muted">{{ object.published_at|date:"F d, Y" }}</small>

          <h2 class="article-title">{{ object.title }}</h2>
          <hr>
          <br>
          <img style='' src="{{ object.image.url }}" width="400" height="250">
          <br>
          <p class="article-content" style="color: black;">{{ object.contents|safe}}</p>
          <br>
          <video width='400' controls>
            <source src="{{ object.video.url }}" type='video/mp4'>
            Your browser does not support the video tag.
          </video>
          <br>
          <hr>
          {% if user.is_authenticated %}
          <div style="text-align:right">
            <a href="{% url 'blog:blog_update' object.id %}"><i class="material-icons" title="Edit">&#xE254;</i></a>
            <!-- <a href="{% url 'blog:blog_delete' object.id %}"><i class="material-icons" style="color:red;"
                title="Delete">&#xE872;</i></a> -->
          </div>
          {% endif %}
          <a href="{{ object.url }}" target="_blank">{{ object.url_text }}</a>
        </div>
        {% include 'blogs/blog_like.html' with data=data %}
      </div>
    </article>
  </div>
</div>
{% endblock content %}

buildblog/templates/blogs/blog_like.html
{% if user.is_authenticated %}
<button class="btn btn-link text-dark p-0 border-0 btn-outline-light" id="like-button" value="{{object.id}}">
  <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-heart" fill="currentColor"
    xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd"
      d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
  </svg>
</button>
<strong class="text-secondary" id="like_count">{{ result }}</strong>
{% endif %}

buildblog/templates/blogs/blog_list.html
{% extends "__base.html" %}
{% load static %}

{% block content %}
    {% include "blogs/_partial_list.html" with page_title=page_title tech_slug=tech_slug %}
    {% include "blogs/share_section.html" %}
{% endblock content %}

buildblog/templates/blogs/listing_page.html
{% extends "__base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/trends_listing.css' %}">
{% endblock extra_css %}

{% block content %}
<div class="trendsHeader">
    <div class="contentSection">
        <div class="darkHeadingBox">
            {% if user.is_authenticated %}
                <a mode="light" class="darkHeading" href="{% url 'blog:blog_create' %}">Make your Build Blog<div class="headingBox">Pro</div></a>
            {% else %}
                <a mode="light" class="darkHeading"  href="{% url 'core:login' %}?next={{request.path}}">Make your Build Blog<div class="headingBox">Pro</div></a>
            {% endif %}

        </div>

        <div class="joinBox">
            <h1>Discover the best developer blogs on any tech stack</h1>
            <div mode="light" class="text">Discover the best developer blogs on any tech stack</div>
            <div mode="light" class=" trendText"> <a href="#">How it Works</a></div>
        </div>
    </div>
</div>
<div>
    <div pattern="topography" class="css-1n7gx3f">
    </div>
</div>
</div>

<div class="trendsContainer">
    <div id="all-topics" class="discoverSection">
        <div class="discoverSectionListing">
            <div class="discoverHeadingDiv">
                <h2>Discover more developer blogs</h2>
                <div>
                    <div class="discoverSearchField">
                        <div class="searchInputDiv">
                            <div class="searchIconDiv">
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round">
                                    <circle cx="11" cy="11" r="8"></circle>
                                    <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                                </svg>
                            </div>
                           <form method="get" action="">
                            <input type="search" aria-invalid="false" id="search" name="keyword"
                                placeholder="&nbsp;Search by technology" class="searchInputField" />
                           </form>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="listingSection">
                    {% for tech in techs %}
                    <div class="discoverListCard">
                        <a href="{% url 'blog:blog_list' tech.slug %}">
                            <span>
                                <span class="svg-wrapper">

                                    {% if tech.icon %}
                                        <img src="{{ tech.icon.url}}" />
                                    {% else %}
                                        <img src="{% static 'img/blogging-platform.svg' %} ">
                                    {% endif %}

                                </span>{{tech.name}}
                            </span>
                            <span class="discoverCardText"><span>100</span>
                                <span class="discoverGreenIcon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline><polyline points="17 6 23 6 23 12"></polyline></svg>
                                </span>
                            </span>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="discoverBlog">
    <div>
        <h2>Claim your blog</h2>
        <p>If your blog's been submitted by someone else and you want to update its categories or description, send an
            email to trends@bloggingfordevs.com via the email address listed on your website ✌️</p>
    </div>
    <div>
        <h2>Share this resource</h2>
        <p>The more people know about Trends, the more developers' blogs are discovered and followed. Help us get the
            word out!</p>
        <a class="mt-3 mb-3" tabindex="0" aria-disabled="false"
            href="http://www.linkedin.com/shareArticle?url=https://73d4-2401-4900-55ab-a63b-649e-d15c-bb02-e305.in.ngrok.io{{ request.get_full_path|urlencode }}"
            target="_blank">
            <button tabindex="0" type="button">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 110 110" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path fill="#0076b2"
                            d="M116 3H12a8.91 8.91 0 00-9 8.8v104.42a8.91 8.91 0 009 8.78h104a8.93 8.93 0 009-8.81V11.77A8.93 8.93 0 00116 3z">
                        </path>
                        <path fill="#fff"
                            d="M21.06 48.73h18.11V107H21.06zm9.06-29a10.5 10.5 0 11-10.5 10.49 10.5 10.5 0 0110.5-10.49M50.53 48.73h17.36v8h.24c2.42-4.58 8.32-9.41 17.13-9.41C103.6 47.28 107 59.35 107 75v32H88.89V78.65c0-6.75-.12-15.44-9.41-15.44s-10.87 7.36-10.87 15V107H50.53z">
                        </path>
                    </svg> &nbsp; Share this on LinkedIn
                </span>
                <span class="MuiTouchRipple-root"></span>
            </button>
        </a>
    </div>
    <div>
        <h2>Acknowledgements</h2>
        <p>These rankings were originally inspired by the Detailed.com list of
            <!-- --> <a href="https://detailed.com/50/" target="_blank">best blogs</a>. SVG Patterns are from
            <!-- --> <a href="https://www.heropatterns.com/" target="_blank">Hero Patterns</a> <!-- -->and many icons
            are from
            <!-- --> <a href="https://devicon.dev/" target="_blank">Devicon</a>. Thanks also to everyone who's submitted
            blogs and shared their feedback!
        </p>
    </div>
</div>
{% endblock content %}
{% block extra_js %}
<script>
    $(document).ready(function () {
        var isOpen = false;
        $('.fa-angle-down').show();
        $(".fa-angle-up").hide();
        $('.card-header').click(function () {
            if (isOpen == false) {
                isOpen = true;
                $(this).find('.fa-angle-down').css("display", "block");
                $(this).find(".fa-angle-up").css("display", "none");
            } else {
                isOpen = false;

                $(this).find('.fa-angle-down').css("display", "none");
                $(this).find(".fa-angle-up").css("display", "block");
            }
        });
    });
</script>

{% endblock extra_js %}